version: "3.9"

services:
  redis:
    image: redis
    container_name: lock-redis
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: lock-api
    ports:
      - "5021:80"
    environment:
      - redis=lock-redis
    depends_on:
      redis:
        condition: service_started